server:
  shutdown: graceful
  port: ${SERVER_PORT:8080}

spring:
  threads:
    virtual:
      enabled: true

logging:
  level:
    root: DEBUG

fuzzy:
  close-match-threshold: ${FUZZ_CLOSE_MATCH_THRESHOLD:0.8}
